# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

author: Jing (Roy) Yang
author_other: 杨靖
title: Jing (Roy) Yang
email: roy.j.yang@qut.edu.au
motto: >
  <a href="https://en.wikipedia.org/wiki/Fan_Zhongyan#Literary_works"
  target="_blank">“不以物喜，不以己悲”（<宋>范仲淹 1046）</a>
description: > # this means to ignore newlines until "url:"
  Welcome to my personal webpage
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>.
  Based on <a href="https://github.com/alshedivat/al-folio">al-folio</a>.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

# the base hostname & protocol for your site
url: 
# the subpath of your site, e.g. /blog/
baseurl: 
# set to true if you want to display last updated in the footer
last_updated: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false
# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: roy-jingyang # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: roy-jingyang
scholar_userid: #Ms1FNhsAAAAJ # your Google Scholar ID
orcid_id: 0000-0001-9218-6954 # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL

cv_filename: YANG_cv_en.pdf

contact_note: >

google_analytics: # your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

# your blog must have a name for it to show up in the nav bar
blog_name:
blog_description:
permalink: #/blog/:year/:title/

# Pagination
pagination:
  enabled: true

# Comments
disqus_shortname: # put your disqus shortname

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate-v2
  - jekyll/scholar
  - jemoji
  - jekyll-seo-tag
  # - bootstrap
  # - material-sass

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Yang
  first_name: [Jing, J., Roy, R.]

  style: apa
  locale: en

  sort_by: year, month
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:  false
enable_katex:             true
enable_mansory:           true
enable_progressbar:       true
enable_tooltips:          true
show_social_icons:        true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.8.6"
  integrity: "sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw="
bootstrap:
  version: "4.4.1"
  integrity:
    css: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    js: "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
fontawesome:
  version: "5.13.0"
  integrity: "sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ="
jquery:
  version: "3.4.1"
  integrity: "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
katex:
  version: "0.11.1"
  integrity:
    css: "sha256-V8SV2MO1FUb63Bwht5Wx9x6PVHNa02gv8BgH/uH3ung="
    js: "sha256-F/Xda58SPdcUCr+xhSGz9MA2zQBPb0ASEYKohl8UCHc="
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="

# MDBootstrap disabled (unknown compliance issue when using popovers)
#mdb:
#  version: "4.17.0"
#  integrity:
#    css: "sha256-/SwJ2GDcEt5382i8zqDwl36VJGECxEoIcBIuoLmLR4g="
#    js: "sha256-UGNYR+uy841zU5TiO2yXD96UktHt9TM4/WXvsDLr4l0="
popper:
  version: "1.12.9"
  integrity: "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
  